Fixed database connection
Bijelic03/SocialMediaBackend pull request #3
Opened 2024-03-21 15:02 UTC by Bijelic03

2024-03-21 15:14 UTC, markonikolic-nqode requested changes

2024-03-21 15:14 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/model/User.java
> +import jakarta.persistence.*;
Pls avoid star imports

2024-03-21 15:14 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/model/User.java
> +public class User implements Serializable {
Still not working without Serializable?

2024-03-22 07:42 UTC, Bijelic03 commented on src/main/java/com/internship/socialnetwork/model/User.java
> +public class User implements Serializable {
I tried to make it without, but it didn't work.

2024-03-22 07:48 UTC, markonikolic-nqode approved these changes

2024-03-22 07:49 UTC, merged

2024-03-22 07:50 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/model/User.java
> +public class User implements Serializable {
Okay, let's move on like this for now, but it's a workaround, not a real solution, just FYI.