Feature/user crud
Bijelic03/SocialMediaBackend pull request #7
Opened 2024-03-25 14:09 UTC by Bijelic03

2024-03-25 14:32 UTC, markonikolic-nqode requested changes

2024-03-25 14:32 UTC, markonikolic-nqode commented on pom.xml
> +        <dependency>
Not needed, since you are already using Jupiter

2024-03-25 14:32 UTC, markonikolic-nqode commented on pom.xml
> +        <dependency>
This should already exist in spring-boot-starter-test

2024-03-25 14:32 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/controller/UserController.java
> +@RequestMapping("/users")
Pls put /api/v1/users

2024-03-25 14:32 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/controller/UserController.java
> +    public ResponseEntity deleteUser(@PathVariable Long id) {
You can use ResponseEntity<Void> to avoid IntelliJ warning

2024-03-25 14:32 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/dto/UserDto.java
> +    @NonNull
You should use @NotNull from Jakarta validations api package

2024-03-25 14:32 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/dto/UserDto.java
> +    public User covertToModel() {
typo

2024-03-25 14:32 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/model/User.java
> +@NoArgsConstructor@Entity
@Entity below

2024-03-25 14:32 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/repository/UserRepository.java
> +    Optional<User> findByUsername(String username);
This one is not needed since you have it in the below method

2024-03-25 14:32 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/service/impl/UserServiceImpl.java
> +        return userRepository.findById(id).orElseThrow(() -> new NotFoundException("User not found!"));
Pls include id in the exception message

2024-03-25 14:32 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/service/impl/UserServiceImpl.java
> +        return userRepository.findAll().stream().map(UserDto::convertToDto).collect(Collectors.toList());
.toList() instead of .collect...

2024-03-25 15:42 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/exception/InternalServerException.java
> +    private final Logger logger = LoggerFactory.getLogger(this.getClass());
You can use @Slf4j annotation instead

2024-03-25 15:42 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/exception/NotFoundException.java
> +    private final Logger logger = LoggerFactory.getLogger(this.getClass());
The same here

2024-03-25 15:44 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/service/impl/UserServiceImpl.java
> +        return UserDto.convertToDto(getUserModel((id)));
You can use static import convertToDto since you are using it in multiple places

2024-03-25 15:44 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/service/impl/UserServiceImpl.java
> +        User user = userDto.covertToModel();
user variable not needed

2024-03-25 15:45 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/service/impl/UserServiceImpl.java
> +        User user = getUserModel(id);
user variable not needed

2024-03-25 15:45 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/impl/UserServiceImplTest.java
> +import static org.mockito.Mockito.*;
Pls avoid star imports

2024-03-25 15:46 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/impl/UserServiceImplTest.java
> +    private  final String surname1 = "Doe";
private final (extra space)

2024-03-25 15:46 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/impl/UserServiceImplTest.java
> +public class UserServiceImplTest {
public not needed

2024-03-25 15:47 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/impl/UserServiceImplTest.java
> +    public void setUp() {
Not needed

2024-03-25 15:47 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/impl/UserServiceImplTest.java
> +    public void shouldGetUser() {
void instead of public void for all tests

2024-03-25 15:48 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/impl/UserServiceImplTest.java
> +import org.junit.Test;
The test is not going to work since you are mixing JUnit4 and JUnit 5(jupiter) annotations. Pls run them before commit

2024-03-25 15:49 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/impl/UserServiceImplTest.java
> +        User user = new User();
Pls use given, when, then, and comments for all tests, check with your colleagues for example. Also verify calls should be used after every test

2024-03-25 15:50 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/impl/UserServiceImplTest.java
> +    public void testCreateUser_Success() {
test not needed in the test name, can be only shouldCreateUser()

2024-03-25 15:53 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/impl/UserServiceImplTest.java
> +    @Test(expected = BadRequestException.class)
You can also validate exception message, once you use assertThrows with JUnit 5 code

2024-03-25 15:53 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/impl/UserServiceImplTest.java
> +        assertNotNull(user1);
Pls divide setup, method call and asserts with a blank line and comments mentioned above

2024-03-25 15:54 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/impl/UserServiceImplTest.java
> +
Unnecessary lines

2024-03-26 10:04 UTC, vkotarlic requested changes

2024-03-26 10:04 UTC, vkotarlic commented on src/main/java/com/internship/socialnetwork/controller/UserController.java
> +    public ResponseEntity deleteUser(@PathVariable Long id) {
There is no need for adding User in all method names we know we work with user

2024-03-27 08:37 UTC, markonikolic-nqode requested changes

2024-03-27 08:37 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/service/impl/UserServiceImpl.java
> +    public List<UserDto> getAllUsers() {
MIssing @Override on all methods

2024-03-27 08:37 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/model/User.java
> +
Extra line

2024-03-27 08:37 UTC, markonikolic-nqode commented on pom.xml
> +		<dependency>
Pls format dependencies, junit jupiter is not needed here as it allready exists in spring-boot-starter-test. Also junit one can be removed

2024-03-27 09:45 UTC, markonikolic-nqode approved these changes

2024-03-27 10:21 UTC, merged