Feature/post crud
Bijelic03/SocialMediaBackend pull request #8
Opened 2024-03-27 11:42 UTC by Bijelic03

2024-03-27 12:17 UTC, markonikolic-nqode requested changes

2024-03-27 12:17 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/controller/PostController.java
> +    @GetMapping("/user/{id}")
Move this to userController, we should use plural as RESTful names.

2024-03-27 12:17 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/controller/PostController.java
> +        return ResponseEntity.ok(postService.create(postDto));
Create should return 201

2024-03-27 12:17 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/repository/PostRepository.java
> +    List<Post> findByAuthor(@Param("author_id") Long authorId);
@Param("author_id") not needed, just use the same value authorId in the query too

2024-03-27 12:17 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/service/PostService.java
> +    List<PostDto> getAllByAuthorId(Long id);
Pls rename parameter to authorId

2024-03-27 12:17 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/service/impl/PostServiceImpl.java
> +        return postRepository.findById(id).orElseThrow(() -> new NotFoundException("Post with id: " + id + " not found!"));
This string can be a constant, you can use String.format for interpolating id value

2024-03-27 12:17 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/service/impl/PostServiceImpl.java
> +        return PostDto.convertToDto(postRepository.findById(id).orElseThrow(() -> new NotFoundException("Post with id: " + id + " not found!")));
convertToDto can be a static import

2024-03-27 12:17 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/service/impl/PostServiceImpl.java
> +        Post post = postDto.convertToModel();
post variable not needed

2024-03-27 12:17 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/service/impl/PostServiceImpl.java
> +        postRepository.findById(id).orElseThrow(() -> new NotFoundException("Post with id: " + id + " not found!"));
you don't need to search by id 2x, the method below also does find by id. You can put postRepository.delete(getModel(id)) instead

2024-03-27 12:17 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +public class PostServiceImplTest {
public not needed

2024-03-27 12:17 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +    private User createAuthor(Long id, String username) {
private methods should be below tests

2024-03-27 12:17 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +        List<Post> posts = new ArrayList<>();
List.of instead

2024-03-27 12:17 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +        List<Post> posts = new ArrayList<>();
The same here

2024-03-27 12:17 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +        Post savedPost = Post.builder()
you can use createPost method here

2024-03-27 12:17 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +        verify(postRepository, times(1)).deleteById(id1);
here you should verify findById too

2024-03-27 12:17 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +        verify(postRepository, never()).deleteById(any());
the same here

2024-03-27 12:17 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +        assertEquals("Post with id: 1 not found!", exception.getMessage());
Can be a constant

2024-03-27 14:37 UTC, vkotarlic requested changes

2024-03-27 14:37 UTC, vkotarlic commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +        }};
Use one way to create objects in our case we asked for Builder and this should be used everywhere.

2024-03-27 14:37 UTC, vkotarlic commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +        }};
Use one way to create objects in our case we asked for Builder and this should be used everywhere.

2024-03-28 07:35 UTC, markonikolic-nqode commented
Pls fix conflicts and pending comments, also you have 2 commits with very similar message

2024-03-28 11:16 UTC, vkotarlic requested changes

2024-03-28 11:16 UTC, vkotarlic commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +    private final String text2 = "Text2";
Do we really need to create variables named like this for numbers and random text

2024-03-28 11:16 UTC, vkotarlic commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +    void shouldGetPost(){
Test name is not consistent with rest of method names in this test class. According to naming standard used below this should be named: `shouldGetPost_whenGetPost_ifPostExists`

2024-03-28 11:16 UTC, vkotarlic commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +    void shouldGetAllPosts() {
Same as above for `shouldGetPost`

2024-03-28 11:16 UTC, vkotarlic commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +    void shouldGetAllPostsBySameAuthor() {
Same as above for `shouldGetPost`

2024-03-28 11:16 UTC, vkotarlic commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +    void shouldCreatePost() {
Same as above for `shouldGetPost`

2024-03-28 11:16 UTC, vkotarlic commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +    void shouldDeletePost() {
Same as above for `shouldGetPost`

2024-03-28 11:16 UTC, vkotarlic commented on src/main/java/com/internship/socialnetwork/service/impl/PostServiceImpl.java
> +    private final String notFoundExceptionMessage = "Post with id: %1$s not found!";
If final (constant) this should be in upper case

2024-03-29 08:24 UTC, markonikolic-nqode requested changes
Pls fix conflicts before requesting a review. Also you have 2 commits with the identical message

2024-03-29 08:45 UTC, markonikolic-nqode requested changes

2024-03-29 08:45 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/controller/PostController.java
> +        return ResponseEntity.status(201).body(postService.create(postDto));
You don't have to hardcode 201, use this instead: ResponseEntity.status(HttpStatus.CREATED)

2024-03-29 08:45 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/service/impl/PostServiceImpl.java
> +    private static final String NOT_FOUND_EXCEPTION_MESSAGE = "Post with id: %1$s not found!";
Constants should be above injected repos or services, just below class declaration

2024-03-29 08:45 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +    private static final String ID_NOT_FOUND = "Post with id: %1$s not found!";
Pls move this below class declaration

2024-03-29 08:45 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +    private final User author = User.builder()
Pls use private methods to build entities here

2024-03-29 08:45 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +        List<Post> posts = List.of(
posts variable not needed

2024-03-29 08:45 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +        List<Post> posts = List.of(
posts variable not needed

2024-03-29 11:08 UTC, vkotarlic requested changes
Overall good job, keep it up! 😄

2024-03-29 11:08 UTC, vkotarlic commented on src/main/java/com/internship/socialnetwork/dto/PostDto.java
> +@NoArgsConstructor
Please try to sort annotations in some order for example `@Data, @Builder, @NoArgs, @AllArgs`

2024-03-29 11:08 UTC, vkotarlic commented on src/main/java/com/internship/socialnetwork/model/Post.java
>  @Entity
Same as above, but `@Entity` should always be on class

2024-03-29 11:08 UTC, vkotarlic commented on src/main/java/com/internship/socialnetwork/model/User.java
>  @Table(name = "`user`")
Why we have `@Builder` two times

2024-03-29 11:08 UTC, vkotarlic commented on src/main/java/com/internship/socialnetwork/service/impl/PostServiceImpl.java
> +        return postRepository.findById(id).orElseThrow(() -> new NotFoundException(String.format(NOT_FOUND_EXCEPTION_MESSAGE, id)));
Please break line at `.orElseThrow()`, always try to break code so it is not crossing grey line in IntellJ

2024-03-29 11:08 UTC, vkotarlic commented on src/main/java/com/internship/socialnetwork/service/impl/PostServiceImpl.java
> +        return postRepository.findAll().stream().map(PostDto::convertToDto).toList();
Same as above

2024-03-29 11:08 UTC, vkotarlic commented on src/main/java/com/internship/socialnetwork/service/impl/PostServiceImpl.java
> +        return postRepository.findByAuthor(authorId).stream().map(PostDto::convertToDto).toList();
Same as above

2024-03-29 11:08 UTC, vkotarlic commented on src/main/java/com/internship/socialnetwork/service/impl/PostServiceImpl.java
> +        return convertToDto(postRepository.findById(id).orElseThrow(() -> new NotFoundException(String.format(NOT_FOUND_EXCEPTION_MESSAGE, id))));
Same as above

2024-03-29 11:08 UTC, vkotarlic commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +    void shouldReturnAllPosts_whenGetAll() {
Test name is not consistent with rest of class, you are missing `_IfPostsExist`

2024-03-29 11:08 UTC, vkotarlic commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +    void shouldReturnAllPostsBySameAuthor_whenGetAllByAuthorId() {
Same as above

2024-03-29 11:08 UTC, vkotarlic commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +    void shouldCreatePost_whenCreate() {
Same as above

2024-03-29 11:08 UTC, vkotarlic commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +    void shouldDeletePost_whenDelete() {
Same as above

2024-04-01 07:28 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/service/impl/PostServiceImpl.java
> +    private static final String NOT_FOUND_EXCEPTION_MESSAGE = "Post with id: %1$s not found!";
ALso the message should bi renamed to POST_NOT_FOUND or POST_NOT_FOUND_(MSG, ERROR). Whatever you choose but then just follow the same format, not somewhere with _MSG and somewhere without it

2024-04-01 07:30 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/PostServiceImplTest.java
> +    private static final String ID_NOT_FOUND = "Post with id: %1$s not found!";
Now that you hardcoded 1 you don't need to call String.format when using this constant

2024-04-01 07:33 UTC, markonikolic-nqode requested changes

2024-04-01 07:33 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/impl/PostServiceImplTest.java
> +        assertEquals(String.format(ID_NOT_FOUND), exception.getMessage());
String.format not needed now that you have hardcoded userId

2024-04-01 07:33 UTC, markonikolic-nqode commented on src/test/java/com/internship/socialnetwork/service/impl/PostServiceImplTest.java
> +    void shouldReturnPost_whenGetPost_ifPostExists(){
space needed: () {

2024-04-01 07:50 UTC, markonikolic-nqode commented on src/main/java/com/internship/socialnetwork/service/impl/PostServiceImpl.java
> +    private static final String NOT_FOUND_EXCEPTION_MESSAGE = "Post with id: %1$s not found!";
Should be Post with id %s not found! Also check other comment about rename

2024-04-01 08:49 UTC, markonikolic-nqode approved these changes

2024-04-01 09:07 UTC, vkotarlic requested changes

2024-04-01 09:07 UTC, vkotarlic commented on src/main/java/com/internship/socialnetwork/repository/PostRepository.java
> +    @Query("SELECT p FROM Post p WHERE p.author = :authorId")
Did you check this? I think you need `p.author.id` here

2024-04-01 09:07 UTC, vkotarlic commented on src/test/java/com/internship/socialnetwork/service/impl/PostServiceImplTest.java
> +    private final Post otherPost = createPost(2L);
Do you need variables here, you can just call these methods where you need them

2024-04-01 13:31 UTC, vkotarlic approved these changes

2024-04-01 13:32 UTC, merged